/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "box_2.h"

/* Function declarations */
CLIENT *rpc_setup(char *host);
box_results *box(CLIENT *clnt, float l, float w, float h);
float *price(CLIENT *clnt, float v, float m);

int main (int argc, char *argv[])
{
	CLIENT *clnt;	/* Client handler */
	char *host;
	float l, w, h, m;	/* Box dimensions and mass */
	box_results *boxresults;
	float *mailprice;


	if (argc != 6) {
		printf ("usage: %s remote_server_host length width height mass \n", 
			argv[0]);
		exit (1);
	}
	host = argv[1];
	if ((l = atof(argv[2])) == 0 && *argv[2] != '0')
	{
		fprintf(stderr, "Invalid value %s\n", argv[2]);
		exit(1);
	}
	if ((w = atof(argv[3])) == 0 && *argv[3] != '0')
	{
		fprintf(stderr, "Invalid value %s\n", argv[3]);
		exit(1);
	}
	if ((h = atof(argv[4])) == 0 && *argv[4] != '0')
	{
		fprintf(stderr, "Invalid value %s\n", argv[4]);
		exit(1);
	}
	if ((m = atof(argv[5])) == 0 && *argv[5] != '0')
	{
		fprintf(stderr, "Invalid value %s\n", argv[5]);
		exit(1);
	}

	if ((clnt = rpc_setup(host)) == 0)
	{
		fprintf(stderr, "Cannot connect to remote_server_host\n");
		exit(1);
	}
	boxresults = box(clnt, l, w, h);
	mailprice = price(clnt, boxresults->volume, m);
	clnt_destroy(clnt);
	exit (0);
}

/* Create client handler, input is string and output is client pointer
 * if client cannot be created, client will force exit
 */
CLIENT *rpc_setup(char *host)
{
	CLIENT *clnt = clnt_create(host, RPC_BOX BOXVERSION2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	return clnt;
}

/* Returns struct box_results pointer by calling remote procedure. Input is 
   three floats and output is box_result struct pointer.*/
box_results *box(CLIENT *clnt, float l, float w, float h)
{
	dimensions dim;
	box_results *result;

	dim.length = l;
	dim.width = w;
	dim.height = h;

	result = box_calc_2(&dim, clnt);
	if (result == NULL)
	{
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Volume: %f and surface area: %f\n", result->volume, 
		       result->surface);
	}
	return result;
}

/* Returns the price of the box based on volume and dimension. Input is two
   to floats and the return value is a float pointer generated from remote
   procedure call */
float *price(CLIENT *clnt, float v, float m)
{
	mail_dims maildim;
	float *price;

	maildim.volume = v;
	maildim.mass = m;
	
	price = mail_calc_2(&maildim, clnt);
	if (price == NULL)
	{
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Box price: %f\n", *price);
	}
	return price;

}
